# Generated by Django 4.2.5 on 2023-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notatki', '0003_remove_komentarz_autor_remove_komentarz_notatka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='notatka',
            name='tagi',
            field=models.ManyToManyField(blank=True, to='notatki.tag'),
        ),
    ]
