# Generated by Django 4.2.5 on 2023-09-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notatki', '0004_tag_notatka_tagi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulubione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notatka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notatki.notatka')),
            ],
        ),
    ]
